(() => {
  const API=window.SmartPortAPI;
  const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const lines=v=>esc(v||'').replace(/\n/g,'<br>');
  let data=null,currentGroup='ALL';
  const canWrite=()=>!!window.SMARTPORT_ACCESS?.can_write;

  function token(){return sessionStorage.getItem('smartport.session')||''}
  async function req(path,options={}){
    const res=await fetch(API.getBase()+path,{credentials:'include',headers:{'Content-Type':'application/json',...(token()?{'Authorization':`Bearer ${token()}`}:{})},...options});
    if(!res.ok)throw new Error(`API ${res.status}: ${await res.text()}`);return res.status===204?null:res.json();
  }
  function toast(msg){const el=document.getElementById('toast');if(!el)return;el.textContent=msg;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),4200)}

  function installViews(){
    const nav=document.querySelector('.nav'),main=document.querySelector('main');if(!nav||!main||document.getElementById('reference'))return;
    const settingsBtn=nav.querySelector('[data-view="settings"]');
    const refBtn=document.createElement('button');refBtn.dataset.view='reference';refBtn.textContent='ACL / Maturity';
    const trBtn=document.createElement('button');trBtn.dataset.view='tr';trBtn.textContent='Technical Requirements';
    nav.insertBefore(refBtn,settingsBtn||null);nav.insertBefore(trBtn,settingsBtn||null);
    const ref=document.createElement('section');ref.id='reference';ref.className='view';ref.innerHTML=`<div class="panel"><div class="panel-title">ACL / FSR Maturity Reference <div class="toolbar"><span class="revision-badge">Project-defined reference</span><span id="refEditMode" class="muted"></span></div></div><div id="referenceBody" style="padding:14px"><div class="muted">載入中...</div></div></div>`;
    const tr=document.createElement('section');tr.id='tr';tr.className='view';tr.innerHTML=`<div class="panel"><div class="panel-title">Technical Requirements <div class="toolbar" id="trFilters"></div></div><div id="trBody" style="padding:14px"><div class="muted">載入中...</div></div></div>`;
    const settings=document.getElementById('settings');main.insertBefore(ref,settings||null);main.insertBefore(tr,settings||null);
  }

  function editModal(title,fields,onSave){
    let modal=document.getElementById('refEditModal');if(modal)modal.remove();
    modal=document.createElement('div');modal.id='refEditModal';modal.className='ref-modal-backdrop';
    modal.innerHTML=`<div class="ref-modal"><div class="ref-modal-head"><strong>${esc(title)}</strong><button type="button" class="btn" data-ref-close>✕</button></div><form id="refEditForm" class="ref-modal-body">${fields.map(f=>f.type==='textarea'?`<div class="field"><label>${esc(f.label)}</label><textarea name="${esc(f.name)}" rows="${f.rows||4}">${esc(f.value||'')}</textarea></div>`:f.type==='select'?`<div class="field"><label>${esc(f.label)}</label><select name="${esc(f.name)}">${f.options.map(x=>`<option ${String(x)===String(f.value)?'selected':''}>${esc(x)}</option>`).join('')}</select></div>`:`<div class="field"><label>${esc(f.label)}</label><input name="${esc(f.name)}" value="${esc(f.value||'')}"></div>`).join('')}<div class="field"><button class="btn primary" type="submit">儲存到 GitHub</button> <button class="btn" type="button" data-ref-close>取消</button></div></form></div>`;
    document.body.appendChild(modal);
    modal.addEventListener('click',e=>{if(e.target===modal||e.target.closest('[data-ref-close]'))modal.remove()});
    modal.querySelector('form').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.currentTarget);try{await onSave(fd);modal.remove();toast('已寫回 GitHub')}catch(err){toast(err.message||err)}};
  }

  async function saveReference(){await req('/api/project/reference/reference-model',{method:'PUT',body:JSON.stringify(data.reference)});}
  async function saveTR(){await req('/api/project/reference/technical-requirements',{method:'PUT',body:JSON.stringify(data.technical_requirements)});}

  async function load(){
    try{data=await req('/api/project/reference');renderReference();renderTR(currentGroup)}catch(e){const msg=`Reference data 載入失敗：${esc(e.message||e)}`;document.getElementById('referenceBody').innerHTML=`<div class="alert">${msg}</div>`;document.getElementById('trBody').innerHTML=`<div class="alert">${msg}</div>`}
  }

  function editMaturity(i){const x=data.reference.fsr_maturity_levels[i];editModal(`編輯 ${x.level}`,['level','name','definition','evidence'].map(k=>({name:k,label:k==='level'?'Level':k==='name'?'Name':k==='definition'?'Definition':'Evidence',value:x[k],type:k==='definition'||k==='evidence'?'textarea':'text'})),async fd=>{for(const k of ['level','name','definition','evidence'])x[k]=String(fd.get(k)||'').trim();await saveReference();renderReference()})}
  function editAcl(i){const x=data.reference.acl_levels[i];editModal(`編輯 ${x.checkpoint} · ${x.level}`,[{name:'checkpoint',label:'Checkpoint',value:x.checkpoint},{name:'date',label:'Date',value:x.date},{name:'level',label:'ACL',value:x.level},{name:'capability',label:'Vehicle Capability',value:x.capability,type:'textarea',rows:6},{name:'review_checks',label:'Review / Check',value:x.review_checks,type:'textarea',rows:6},{name:'fsr_maturity_target',label:'FSR Maturity Target',value:x.fsr_maturity_target}],async fd=>{for(const k of ['checkpoint','date','level','capability','review_checks','fsr_maturity_target'])x[k]=String(fd.get(k)||'').trim();await saveReference();renderReference()})}

  function renderReference(){
    const root=document.getElementById('referenceBody');if(!root||!data)return;const r=data.reference||{},m=r.fsr_maturity_levels||[],acl=r.acl_levels||[],edit=canWrite();
    document.getElementById('refEditMode').textContent=edit?'PM · Editable':'Engineer · Read only';
    root.innerHTML=`<div class="grid2 reference-intro"><div class="alert info"><b>ACL｜Autonomous Capability Level</b><br>${esc(r.acl_note||'')}</div><div class="alert info"><b>FSR Maturity｜M0～M5</b><br>${esc(r.maturity_note||'')}</div></div>
      <div class="panel reference-subpanel"><div class="panel-title">FSR Maturity Model｜M0 → M5</div><div class="maturity-grid">${m.map((x,i)=>`<div class="maturity-card"><div class="maturity-card-head"><div><div class="maturity-code">${esc(x.level)}</div><div class="maturity-name">${esc(x.name)}</div></div>${edit?`<button class="btn smallbtn" data-edit-maturity="${i}">Edit</button>`:''}</div><div class="maturity-def">${esc(x.definition)}</div><div class="muted"><b>Evidence：</b>${esc(x.evidence)}</div></div>`).join('')}</div></div>
      <div class="panel reference-subpanel"><div class="panel-title">ACL Roadmap｜Checkpoint → Vehicle Capability</div><div style="overflow:auto"><table class="reference-table"><thead><tr><th>CP</th><th>ACL</th><th>車輛能力 / Capability</th><th>Review / Check</th><th>FSR Maturity Target</th>${edit?'<th></th>':''}</tr></thead><tbody>${acl.map((x,i)=>`<tr><td><b>${esc(x.checkpoint)}</b><div class="muted">${esc(x.date)}</div></td><td><span class="acl-pill">${esc(x.level)}</span></td><td>${lines(x.capability)}</td><td>${lines(x.review_checks)}</td><td><b>${esc(x.fsr_maturity_target)}</b></td>${edit?`<td><button class="btn smallbtn" data-edit-acl="${i}">Edit</button></td>`:''}</tr>`).join('')}</tbody></table></div></div>`;
  }

  function allRequirements(){return(data?.technical_requirements?.groups||[]).flatMap(g=>(g.requirements||[]).map((x,i)=>({...x,group:g.group,_index:i})))}
  function editRequirement(group,index){const g=data.technical_requirements.groups.find(x=>x.group===group),x=g.requirements[index];editModal(`編輯 ${x.id}`,[{name:'id',label:'TR ID',value:x.id},{name:'requirement',label:'Technical Requirement',value:x.requirement,type:'textarea',rows:5},{name:'source',label:'Source',value:x.source},{name:'parameter',label:'Parameter',value:x.parameter,type:'textarea',rows:3},{name:'verification',label:'Verification',value:x.verification},{name:'status',label:'Status',value:x.status,type:'select',options:['Preliminary','TBD','Approved','Verified','Closed']}],async fd=>{for(const k of ['id','requirement','source','parameter','verification','status'])x[k]=String(fd.get(k)||'').trim();await saveTR();renderTR(currentGroup)})}
  function editJsonSection(key,title){const value=data.technical_requirements[key]||[];editModal(title,[{name:'json',label:'JSON',value:JSON.stringify(value,null,2),type:'textarea',rows:20}],async fd=>{let v;try{v=JSON.parse(String(fd.get('json')||'[]'))}catch(_){throw new Error('JSON 格式錯誤')}data.technical_requirements[key]=v;await saveTR();renderTR(currentGroup)})}

  function renderTR(group){
    currentGroup=group;const root=document.getElementById('trBody'),filters=document.getElementById('trFilters');if(!root||!filters||!data)return;const t=data.technical_requirements||{},groups=t.groups||[],all=allRequirements(),rows=group==='ALL'?all:all.filter(x=>x.group===group),edit=canWrite();
    filters.innerHTML=['ALL',...groups.map(g=>g.group)].map(g=>`<button type="button" class="btn smallbtn ${g===group?'primary':''}" data-tr-group="${esc(g)}">${g==='ALL'?'All · '+all.length:g+' · '+all.filter(x=>x.group===g).length}</button>`).join('')+(edit?'<span class="revision-badge">PM · Editable</span>':'<span class="revision-badge">Read only</span>');
    root.innerHTML=`<div class="alert info"><b>Source：</b>${esc(t.source||'')}<br><b>Status：</b>${esc(t.status||'')}。保留 Preliminary / TBD，不自動視為已核准。</div><div class="tr-summary">${groups.map(g=>`<div class="tr-stat"><b>${esc(g.group)}</b><span>${(g.requirements||[]).length} TR</span></div>`).join('')}</div>
      <div class="panel reference-subpanel"><div class="panel-title">${group==='ALL'?'All Technical Requirements':esc(group)+' Technical Requirements'}</div><div style="overflow:auto;max-height:620px"><table class="reference-table tr-table"><thead><tr><th>TR ID</th><th>Technical Requirement</th><th>Source</th><th>Parameter</th><th>Verification</th><th>Status</th>${edit?'<th></th>':''}</tr></thead><tbody>${rows.map(x=>`<tr><td><b>${esc(x.id)}</b><div class="muted">${esc(x.group)}</div></td><td>${esc(x.requirement)}</td><td>${esc(x.source)}</td><td><code>${lines(x.parameter)}</code></td><td>${esc(x.verification)}</td><td><span class="revision-badge ${x.status==='TBD'?'tr-tbd':''}">${esc(x.status)}</span></td>${edit?`<td><button class="btn smallbtn" data-edit-tr="${esc(x.group)}:${x._index}">Edit</button></td>`:''}</tr>`).join('')}</tbody></table></div></div>${renderInterfaces(t.interfaces||[],edit)}${renderOdd(t.odd_allocation||[],edit)}${renderTrace(t.fsr_traceability||[],t.open_gates||[],edit)}`;
  }

  function renderInterfaces(v,edit){return`<div class="panel reference-subpanel"><div class="panel-title">Cross-Subsystem Interface Technical Requirements ${edit?'<button class="btn smallbtn" data-edit-section="interfaces">Edit section</button>':''}</div><div style="overflow:auto"><table class="reference-table"><thead><tr><th>Interface</th><th>Producer → Consumer</th><th>Required Data</th><th>Technical Requirement</th><th>Verification</th></tr></thead><tbody>${v.map(x=>`<tr><td><b>${esc(x.interface)}</b></td><td>${esc(x.flow)}</td><td>${esc(x.required_data)}</td><td>${esc(x.technical_requirement)}</td><td>${esc(x.verification)}</td></tr>`).join('')}</tbody></table></div></div>`}
  function renderOdd(v,edit){return`<div class="panel reference-subpanel"><div class="panel-title">ODD Parameter → Technical Requirement Allocation ${edit?'<button class="btn smallbtn" data-edit-section="odd_allocation">Edit section</button>':''}</div><div style="overflow:auto"><table class="reference-table"><thead><tr><th>Parameter Family</th><th>Owner</th><th>TR Use</th><th>Symbolic Parameters</th></tr></thead><tbody>${v.map(x=>`<tr><td><b>${esc(x.family)}</b></td><td>${esc(x.owner)}</td><td>${esc(x.tr_use)}</td><td><code>${esc(x.parameters)}</code></td></tr>`).join('')}</tbody></table></div></div>`}
  function renderTrace(trace,gates,edit){return`<div class="grid2 reference-subpanel"><div class="panel"><div class="panel-title">FSR → TR Traceability ${edit?'<button class="btn smallbtn" data-edit-section="fsr_traceability">Edit</button>':''}</div><div style="overflow:auto"><table class="reference-table"><thead><tr><th>FSR Cluster</th><th>Primary</th><th>TR Examples</th><th>Evidence</th></tr></thead><tbody>${trace.map(x=>`<tr><td>${lines(x.cluster)}</td><td>${esc(x.primary_subsystem)}</td><td>${esc(x.tr_examples)}</td><td>${esc(x.evidence_to_close)}</td></tr>`).join('')}</tbody></table></div></div><div class="panel"><div class="panel-title">Open Gates / TBD ${edit?'<button class="btn smallbtn" data-edit-section="open_gates">Edit</button>':''}</div><div style="overflow:auto"><table class="reference-table"><thead><tr><th>Open Item</th><th>Why it matters</th><th>Affected</th></tr></thead><tbody>${gates.map(x=>`<tr><td><b>${esc(x.item)}</b></td><td>${esc(x.why_it_matters)}</td><td>${esc(x.affected_subsystem)}</td></tr>`).join('')}</tbody></table></div></div></div>`}

  document.addEventListener('click',e=>{let b=e.target.closest('[data-tr-group]');if(b){renderTR(b.dataset.trGroup);return}b=e.target.closest('[data-edit-maturity]');if(b){editMaturity(Number(b.dataset.editMaturity));return}b=e.target.closest('[data-edit-acl]');if(b){editAcl(Number(b.dataset.editAcl));return}b=e.target.closest('[data-edit-tr]');if(b){const[g,i]=b.dataset.editTr.split(':');editRequirement(g,Number(i));return}b=e.target.closest('[data-edit-section]');if(b){const titles={interfaces:'Cross-Subsystem Interfaces',odd_allocation:'ODD Allocation',fsr_traceability:'FSR → TR Traceability',open_gates:'Open Gates'};editJsonSection(b.dataset.editSection,titles[b.dataset.editSection]);return}});
  installViews();
  const style=document.createElement('style');style.textContent=`.reference-subpanel{margin-top:14px}.maturity-grid{display:grid;grid-template-columns:repeat(6,minmax(145px,1fr));gap:10px;padding:14px}.maturity-card{border:1px solid var(--line);border-radius:10px;padding:12px;background:#fff}.maturity-card-head{display:flex;justify-content:space-between;gap:8px;align-items:flex-start}.maturity-code{font-size:22px;font-weight:800;color:var(--navy)}.maturity-name{font-weight:700;margin:3px 0 8px}.maturity-def{font-size:13px;line-height:1.45;margin-bottom:9px}.reference-table td{line-height:1.45;min-width:110px}.reference-table td:nth-child(3){min-width:220px}.acl-pill{display:inline-block;padding:4px 8px;border-radius:999px;background:#eef4fb;color:#315f91;font-weight:700}.tr-summary{display:flex;gap:8px;flex-wrap:wrap;margin:10px 0}.tr-stat{border:1px solid var(--line);border-radius:9px;padding:8px 12px;background:#fff}.tr-stat span{display:block;font-size:11px;color:var(--muted);margin-top:2px}.tr-tbd{background:#fff1d8;color:#925f0d}.tr-table code,.reference-table code{font-size:11px;white-space:normal}.ref-modal-backdrop{position:fixed;inset:0;background:rgba(16,24,40,.35);z-index:150;display:flex;align-items:center;justify-content:center;padding:20px}.ref-modal{width:min(760px,96vw);max-height:90vh;background:#fff;border-radius:12px;box-shadow:0 20px 60px rgba(0,0,0,.25);overflow:auto}.ref-modal-head{position:sticky;top:0;background:#fff;padding:14px 16px;border-bottom:1px solid var(--line);display:flex;justify-content:space-between;align-items:center;z-index:2}.ref-modal-body{padding:16px}@media(max-width:1200px){.maturity-grid{grid-template-columns:repeat(3,1fr)}}`;document.head.appendChild(style);
  setTimeout(load,200);
})();
